# Generated by Django 6.0.6 on 2026-06-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('beauty', 'Beauty'), ('technology', 'Technology')], default='women', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=49.9, max_digits=10),
        ),
    ]
